kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  name: yoshihiro-iwazaki-pvc
  namespace: yoshihiro-iwazaki--pipeline-from-scratch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

